language: python
python:
  - "3.7"
  - "3.8"

addons:
  apt:
    packages:
      - libhdf5-dev 

env:
  global:
  - PYTHONPATH="/home/travis/build/pziarsolo/variation6"
  - PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install coveralls radon

script:
  - coverage run --source=. -m unittest discover -s variation6/tests

after_success:
  - coveralls

